version: "3.7"

services:
  oauthserver:
    image: oauthserver
    build:
      context: .
      dockerfile: ./samples/OAuthServer/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - mynetwork

  client1:
    image: client1
    build:
      context: .
      dockerfile: ./samples/Client1/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    networks:
      - mynetwork
      
networks:
  mynetwork:
    name: mynetwork-network
